import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "../styles/styles.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Cinépolis App</h1>
        <p>Hello world!</p>
        {children}
      </body>
    </html>
  );
}
